"""Compare a MultiMIDAS forecast with its stored snapshot.

The test runs one vintage of the MultiMIDAS model on mixed-frequency data with
multiple regressors and compares the output with the stored snapshot.
"""

import pytest

pytest.importorskip("nowcast_midas")

import forecast_evaluation as fe
import forecast_realtime as rt

from .sample_data import sample_midas_data

pytestmark = [pytest.mark.pipeline, pytest.mark.midas]

# Use the second monthly regressor generated by forecast_realtime.
NOISY_VAR = "var_monthly_b"


@pytest.fixture()
def multimidas_data():
    return sample_midas_data()


def test_multimidas_data(multimidas_data, snapshot):
    """Run a MultiMIDAS model on one vintage and compare the snapshot."""

    data = fe.NowcastData(outturns_data=multimidas_data)

    model = rt.models.ForecastMultiMIDAS(
        variables=["var_monthly_a", NOISY_VAR],
        method="almon",
        n_lags=5,
        estimator="ols",
        horizons=[0, 1],
        n_ar_lags=1,
    )

    rt_model = rt.RealTimeModel(models=model, data=data)

    y_variables = ["var_quarterly_a"]
    X_variables = ["var_monthly_a", NOISY_VAR]
    data_transformation = {
        "var_quarterly_a": "pop",
        "var_monthly_a": "pop",
        NOISY_VAR: "pop",
    }

    rt_model.forecast(
        y_variables=y_variables,
        X_variables=X_variables,
        data_transformation=data_transformation,
        step_frequency="Q",
        first_vintage="2024-01-31",
        last_vintage="2024-06-30",
        X_imputation=None,
    )

    # Extract the model forecasts.
    result = rt_model.data.forecasts
    result = result[result["source"] == "ForecastMultiMIDAS"].copy()
    result = result.sort_values(["variable", "date"]).reset_index(drop=True)

    # Round float columns and normalise -0.0 to 0.0 for stable snapshots.
    float_cols = result.select_dtypes(include="float").columns
    result[float_cols] = result[float_cols].round(6) + 0.0

    assert result.to_dict(orient="list") == snapshot


def test_multimidas_data_decomposition(multimidas_data, snapshot):
    """Compare the MultiMIDAS decomposition with its stored snapshot."""

    data = fe.NowcastData(outturns_data=multimidas_data)

    model = rt.models.ForecastMultiMIDAS(
        variables=["var_monthly_a", NOISY_VAR],
        method="almon",
        n_lags=5,
        estimator="ols",
        horizons=[0, 1],
        n_ar_lags=1,
    )

    rt_model = rt.RealTimeModel(models=model, data=data)

    y_variables = ["var_quarterly_a"]
    X_variables = ["var_monthly_a", NOISY_VAR]
    data_transformation = {
        "var_quarterly_a": "pop",
        "var_monthly_a": "pop",
        NOISY_VAR: "pop",
    }

    rt_model.forecast(
        y_variables=y_variables,
        X_variables=X_variables,
        data_transformation=data_transformation,
        step_frequency="Q",
        first_vintage="2024-01-31",
        last_vintage="2024-06-30",
        decomp=True,
        X_imputation=None,
    )

    # Extract the model decomposition.
    result = rt_model.decompositions
    result = result[result["source"] == "ForecastMultiMIDAS"].copy()
    result = result.sort_values(
        ["date", "vintage_date", "forecast_horizon", "component"]
    ).reset_index(drop=True)

    # Round float columns and normalise -0.0 to 0.0 so cancellation terms do
    # not change sign across platforms and break the exact snapshot.
    float_cols = result.select_dtypes(include="float").columns
    result[float_cols] = result[float_cols].round(6) + 0.0

    assert result.to_dict(orient="list") == snapshot
